repositories:
  - name: gitlab
    url: https://charts.gitlab.io/
  - name: harbor
    url: https://helm.goharbor.io/
  - name: sonarqube
    url: https://SonarSource.github.io/helm-chart-sonarqube

releases:
  - name: gitlab-chart
    namespace: gitlab
    chart: ./gitlab-chart
    timeout: 600
    values:
     - ./gitlab-chart/values.yaml

  - name: harbor
    namespace: gitlab
    chart: ./harbor-chart
    values:
     - ./harbor-chart/values.yaml

  - name: runner
    namespace: gitlab
    chart: ./gitlab-runner-chart
    needs: 
     - harbor
     - gitlab-chart
    values:
     - ./gitlab-runner-chart/values.yaml
  
  - name: sonarqube
    namespace: gitlab
    chart: ./sonarqube-chart
    needs:
      - gitlab-chart
      - runner
    values:
      - ./sonarqube-chart/values.yaml

  - name: push-repo
    namespace: gitlab
    chart: ./push-repo-chart
    needs: 
     - sonarqube
     - runner
    values:
     - ./push-repo-chart/values.yaml
     - repo_token: ""
