repositories:
  - name: gitlab
    url: https://charts.gitlab.io/
  - name: harbor
    url: https://helm.goharbor.io/

releases:
  - name: gitlab-chart
    namespace: gitlab
    chart: ./gitlab-chart
    timeout: 600
    values:
      - ./gitlab-chart/values.yaml

  - name: harbor
    namespace: gitlab
    chart: ./harbor-chart
    values:
      - ./harbor-chart/values.yaml

  - name: runner
    namespace: gitlab
    chart: ./gitlab-runner-chart
    needs: 
      - harbor
      - gitlab-chart
    values:
      - ./gitlab-runner-chart/values.yaml
