apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-job-sa
  namespace: gitlab
  meta.helm.sh/release-name: gitlab-chart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-job-role
  namespace: gitlab
  meta.helm.sh/release-name: gitlab-chart
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "update", "exec"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-job-rolebinding
  namespace: gitlab
  meta.helm.sh/release-name: gitlab-chart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-job-role
subjects:
- kind: ServiceAccount
  name: token-job-sa
  namespace: gitlab

